"""second migrat

Revision ID: 387f1810ae78
Revises: ec2040e70ec8
Create Date: 2018-03-01 21:17:38.636015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387f1810ae78'
down_revision = 'ec2040e70ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    # ### end Alembic commands ###
